-- Agentic Enterprise demo: Snowflake side (product telemetry, use-case knowledge, support KB).
-- Run as ACCOUNTADMIN in a Snowsight worksheet. Safe to re-run.
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS AGENTIC_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Agentic Enterprise demo: Agentforce callouts, Cortex Search refresh, Cortex Analyst';
CREATE DATABASE IF NOT EXISTS AGENTIC_DEMO COMMENT = 'Agentic Enterprise demo (fictional data)';
CREATE SCHEMA IF NOT EXISTS AGENTIC_DEMO.GTM COMMENT = 'Go-to-market: accounts, contracts, telemetry, use cases, KB';
USE WAREHOUSE AGENTIC_WH;
USE SCHEMA AGENTIC_DEMO.GTM;

CREATE OR REPLACE TABLE ACCOUNTS (
  ACCOUNT_KEY VARCHAR COMMENT 'Platform account key',
  ACCOUNT_NAME VARCHAR,
  INDUSTRY VARCHAR,
  EMPLOYEES NUMBER,
  REGION VARCHAR,
  CUSTOMER_SINCE DATE,
  SF_EXT_ID VARCHAR COMMENT 'Salesforce Account.CRM_Score_Ext_Id__c'
) COMMENT = 'Customer accounts of the data-platform vendor';

CREATE OR REPLACE TABLE CONTRACTS (
  ACCOUNT_KEY VARCHAR, TERM_START DATE, TERM_END DATE,
  ANNUAL_CREDITS NUMBER COMMENT 'Committed capacity per contract year',
  LIST_PRICE_PER_CREDIT NUMBER(10,2) COMMENT 'Fictional list rate; for non-binding estimates only'
) COMMENT = 'Capacity contracts';

CREATE OR REPLACE TABLE DAILY_CONSUMPTION (
  ACCOUNT_KEY VARCHAR, USAGE_DATE DATE,
  WORKLOAD VARCHAR COMMENT 'Data Engineering, BI & Analytics, Data Science & ML, AI (Cortex), Data Sharing & Apps',
  WAREHOUSE_NAME VARCHAR, CREDITS NUMBER(12,2), QUERIES NUMBER, ACTIVE_USERS NUMBER
) COMMENT = 'Daily credit consumption by account and workload';

CREATE OR REPLACE TABLE USE_CASE_CATALOG (
  USE_CASE_ID VARCHAR, NAME VARCHAR, BUSINESS_UNIT VARCHAR, INDUSTRIES VARCHAR, DESCRIPTION VARCHAR,
  TYPICAL_ANNUAL_CREDITS NUMBER, TYPICAL_OUTCOME VARCHAR, TIME_TO_VALUE_WEEKS NUMBER, PREREQUISITES VARCHAR
) COMMENT = 'Solution use cases the vendor sells';

CREATE OR REPLACE TABLE CUSTOMER_USE_CASES (
  ACCOUNT_KEY VARCHAR, USE_CASE_ID VARCHAR, STATUS VARCHAR, GO_LIVE_DATE DATE, ANNUAL_CREDITS NUMBER, OUTCOME VARCHAR
) COMMENT = 'Which customers run which use cases, and what they got';

CREATE OR REPLACE TABLE CASE_STUDIES (
  STUDY_ID VARCHAR, TITLE VARCHAR, CUSTOMER VARCHAR, INDUSTRY VARCHAR, USE_CASE_ID VARCHAR, BODY VARCHAR
) COMMENT = 'Customer case studies (unstructured text for Cortex Search)';

CREATE OR REPLACE TABLE SUPPORT_KB (
  ARTICLE_ID VARCHAR, TITLE VARCHAR, PRODUCT_AREA VARCHAR, BODY VARCHAR
) COMMENT = 'Support knowledge base (unstructured text for Cortex Search)';

CREATE STAGE IF NOT EXISTS DEMO_STAGE COMMENT = 'Upload agentforce/data/out/*.csv here';
CREATE FILE FORMAT IF NOT EXISTS DEMO_CSV TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE COMPRESSION = AUTO;
