-- Load the CSVs from agentforce/data/out (upload them to @DEMO_STAGE first), then build the views
-- the Agentforce actions read. Safe to re-run: tables are truncated before loading.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AGENTIC_WH;
USE SCHEMA AGENTIC_DEMO.GTM;

TRUNCATE TABLE ACCOUNTS; TRUNCATE TABLE CONTRACTS; TRUNCATE TABLE DAILY_CONSUMPTION; TRUNCATE TABLE USE_CASE_CATALOG;
TRUNCATE TABLE CUSTOMER_USE_CASES; TRUNCATE TABLE CASE_STUDIES; TRUNCATE TABLE SUPPORT_KB;
COPY INTO ACCOUNTS FROM @DEMO_STAGE/accounts.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO CONTRACTS FROM @DEMO_STAGE/contracts.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO DAILY_CONSUMPTION FROM @DEMO_STAGE/daily_consumption.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO USE_CASE_CATALOG FROM @DEMO_STAGE/use_case_catalog.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO CUSTOMER_USE_CASES FROM @DEMO_STAGE/customer_use_cases.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO CASE_STUDIES FROM @DEMO_STAGE/case_studies.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;
COPY INTO SUPPORT_KB FROM @DEMO_STAGE/support_kb.csv FILE_FORMAT = (FORMAT_NAME = DEMO_CSV) FORCE = TRUE;

-- One row per account: the facts the Agentforce consumption action grounds on.
CREATE OR REPLACE VIEW V_ACCOUNT_CONSUMPTION_SUMMARY
  COMMENT = 'Per-account consumption facts for Agentforce grounding'
AS
WITH as_of_day AS (SELECT MAX(USAGE_DATE) AS D FROM DAILY_CONSUMPTION),
c AS (SELECT dc.*, as_of_day.D FROM DAILY_CONSUMPTION dc CROSS JOIN as_of_day),
agg AS (
  SELECT ACCOUNT_KEY, MAX(D) AS AS_OF_DATE,
         SUM(IFF(USAGE_DATE > DATEADD(day, -365, D), CREDITS, 0)) AS T12,
         SUM(IFF(USAGE_DATE <= DATEADD(day, -365, D) AND USAGE_DATE > DATEADD(day, -730, D), CREDITS, 0)) AS P12,
         SUM(IFF(USAGE_DATE > DATEADD(day, -90, D), CREDITS, 0)) AS L90,
         SUM(IFF(USAGE_DATE <= DATEADD(day, -90, D) AND USAGE_DATE > DATEADD(day, -180, D), CREDITS, 0)) AS P90,
         SUM(IFF(USAGE_DATE > DATEADD(day, -30, D), CREDITS, 0)) / 30 AS RUN_RATE_PER_DAY,
         SUM(IFF(USAGE_DATE > DATEADD(day, -30, D), ACTIVE_USERS, 0)) / 30 AS AVG_DAILY_ACTIVE_USERS
  FROM c GROUP BY ACCOUNT_KEY),
term AS (
  SELECT k.ACCOUNT_KEY, k.TERM_START, k.TERM_END, k.ANNUAL_CREDITS,
         SUM(IFF(dc.USAGE_DATE >= k.TERM_START, dc.CREDITS, 0)) AS CONSUMED_IN_TERM
  FROM CONTRACTS k JOIN DAILY_CONSUMPTION dc ON dc.ACCOUNT_KEY = k.ACCOUNT_KEY
  GROUP BY 1, 2, 3, 4),
wl AS (
  SELECT ACCOUNT_KEY, WORKLOAD,
         SUM(IFF(USAGE_DATE > DATEADD(day, -90, D), CREDITS, 0)) AS L90,
         SUM(IFF(USAGE_DATE <= DATEADD(day, -90, D) AND USAGE_DATE > DATEADD(day, -180, D), CREDITS, 0)) AS P90
  FROM c GROUP BY 1, 2),
top_wl AS (
  SELECT ACCOUNT_KEY, WORKLOAD AS TOP_WORKLOAD, ROUND(100 * L90 / SUM(L90) OVER (PARTITION BY ACCOUNT_KEY)) AS TOP_WORKLOAD_SHARE_PCT
  FROM wl QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_KEY ORDER BY L90 DESC) = 1),
up_wl AS (
  SELECT ACCOUNT_KEY, WORKLOAD AS FASTEST_GROWING_WORKLOAD, ROUND(100 * (L90 / NULLIF(P90, 0) - 1)) AS FASTEST_GROWTH_PCT
  FROM wl WHERE P90 > 100
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_KEY ORDER BY L90 / NULLIF(P90, 0) DESC) = 1),
down_wl AS (
  SELECT ACCOUNT_KEY, WORKLOAD AS DECLINING_WORKLOAD, ROUND(100 * (L90 / NULLIF(P90, 0) - 1)) AS DECLINE_PCT
  FROM wl WHERE P90 > 100 AND L90 < 0.9 * P90
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_KEY ORDER BY L90 / NULLIF(P90, 0) ASC) = 1)
SELECT a.ACCOUNT_KEY, a.ACCOUNT_NAME, a.SF_EXT_ID, a.INDUSTRY,
       g.AS_OF_DATE,
       ROUND(g.T12) AS TRAILING_12M_CREDITS,
       ROUND(100 * (g.T12 / NULLIF(g.P12, 0) - 1), 1) AS YOY_GROWTH_PCT,
       ROUND(100 * (g.L90 / NULLIF(g.P90, 0) - 1), 1) AS LAST_90D_GROWTH_PCT,
       CASE WHEN g.L90 > 1.05 * g.P90 THEN 'Increasing' WHEN g.L90 < 0.95 * g.P90 THEN 'Decreasing' ELSE 'Stable' END
         AS CONSUMPTION_TREND,
       ROUND(g.RUN_RATE_PER_DAY * 365) AS ANNUALIZED_RUN_RATE_CREDITS,
       ROUND(g.AVG_DAILY_ACTIVE_USERS) AS AVG_DAILY_ACTIVE_USERS,
       t.ANNUAL_CREDITS AS CONTRACT_ANNUAL_CREDITS, t.TERM_START, t.TERM_END,
       ROUND(t.CONSUMED_IN_TERM) AS CONSUMED_IN_TERM_CREDITS,
       ROUND(100 * t.CONSUMED_IN_TERM / t.ANNUAL_CREDITS, 1) AS CONTRACT_UTILIZATION_PCT,
       ROUND(100 * (t.CONSUMED_IN_TERM + g.RUN_RATE_PER_DAY * GREATEST(DATEDIFF(day, g.AS_OF_DATE, t.TERM_END), 0))
             / t.ANNUAL_CREDITS, 1) AS PROJECTED_TERM_END_UTILIZATION_PCT,
       IFF(t.CONSUMED_IN_TERM >= t.ANNUAL_CREDITS, g.AS_OF_DATE,
           DATEADD(day, CEIL((t.ANNUAL_CREDITS - t.CONSUMED_IN_TERM) / NULLIF(g.RUN_RATE_PER_DAY, 0)), g.AS_OF_DATE))
         AS PROJECTED_EXHAUSTION_DATE,
       tw.TOP_WORKLOAD, tw.TOP_WORKLOAD_SHARE_PCT,
       uw.FASTEST_GROWING_WORKLOAD, uw.FASTEST_GROWTH_PCT,
       dw.DECLINING_WORKLOAD, dw.DECLINE_PCT
FROM ACCOUNTS a
JOIN agg g ON g.ACCOUNT_KEY = a.ACCOUNT_KEY
JOIN term t ON t.ACCOUNT_KEY = a.ACCOUNT_KEY
LEFT JOIN top_wl tw ON tw.ACCOUNT_KEY = a.ACCOUNT_KEY
LEFT JOIN up_wl uw ON uw.ACCOUNT_KEY = a.ACCOUNT_KEY
LEFT JOIN down_wl dw ON dw.ACCOUNT_KEY = a.ACCOUNT_KEY;

-- Monthly credits by workload, for charts and for CoCo / Cortex Analyst questions.
CREATE OR REPLACE VIEW V_WORKLOAD_MONTHLY
  COMMENT = 'Monthly credits by account and workload'
AS
SELECT a.ACCOUNT_NAME, a.SF_EXT_ID, dc.ACCOUNT_KEY, DATE_TRUNC('month', dc.USAGE_DATE) AS USAGE_MONTH, dc.WORKLOAD,
       ROUND(SUM(dc.CREDITS), 1) AS CREDITS, SUM(dc.QUERIES) AS QUERIES, ROUND(AVG(dc.ACTIVE_USERS)) AS AVG_ACTIVE_USERS
FROM DAILY_CONSUMPTION dc JOIN ACCOUNTS a ON a.ACCOUNT_KEY = dc.ACCOUNT_KEY
GROUP BY 1, 2, 3, 4, 5;

-- Use cases that live peers in the same industry run and this account does not.
CREATE OR REPLACE VIEW V_USE_CASE_RECOMMENDATIONS
  COMMENT = 'Peer-based use-case recommendations with indicative credit estimates'
AS
WITH peer_adoption AS (
  SELECT a.ACCOUNT_KEY, u.USE_CASE_ID,
         COUNT(DISTINCT u.ACCOUNT_KEY) AS PEERS_LIVE,
         MEDIAN(u.ANNUAL_CREDITS) AS PEER_MEDIAN_CREDITS,
         LISTAGG(DISTINCT p.ACCOUNT_NAME, ', ') WITHIN GROUP (ORDER BY p.ACCOUNT_NAME) AS PEER_NAMES,
         LISTAGG(p.ACCOUNT_NAME || ': ' || u.OUTCOME, '; ') WITHIN GROUP (ORDER BY p.ACCOUNT_NAME) AS PEER_OUTCOMES
  FROM ACCOUNTS a
  JOIN ACCOUNTS p ON p.INDUSTRY = a.INDUSTRY AND p.ACCOUNT_KEY <> a.ACCOUNT_KEY
  JOIN CUSTOMER_USE_CASES u ON u.ACCOUNT_KEY = p.ACCOUNT_KEY AND u.STATUS = 'Live'
  GROUP BY 1, 2)
SELECT a.ACCOUNT_KEY, a.ACCOUNT_NAME, a.SF_EXT_ID,
       ROW_NUMBER() OVER (PARTITION BY a.ACCOUNT_KEY ORDER BY pa.PEERS_LIVE DESC, pa.PEER_MEDIAN_CREDITS DESC) AS RANK,
       uc.USE_CASE_ID, uc.NAME AS USE_CASE, uc.BUSINESS_UNIT, uc.DESCRIPTION,
       pa.PEERS_LIVE, pa.PEER_NAMES, pa.PEER_OUTCOMES,
       ROUND(pa.PEER_MEDIAN_CREDITS, -2) AS EST_ANNUAL_CREDITS,
       ROUND(pa.PEER_MEDIAN_CREDITS * k.LIST_PRICE_PER_CREDIT, -3) AS INDICATIVE_ANNUAL_VALUE_USD,
       uc.TYPICAL_OUTCOME, uc.TIME_TO_VALUE_WEEKS, uc.PREREQUISITES
FROM ACCOUNTS a
JOIN peer_adoption pa ON pa.ACCOUNT_KEY = a.ACCOUNT_KEY
JOIN USE_CASE_CATALOG uc ON uc.USE_CASE_ID = pa.USE_CASE_ID
JOIN CONTRACTS k ON k.ACCOUNT_KEY = a.ACCOUNT_KEY
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER_USE_CASES x WHERE x.ACCOUNT_KEY = a.ACCOUNT_KEY AND x.USE_CASE_ID = uc.USE_CASE_ID);

SELECT * FROM V_ACCOUNT_CONSUMPTION_SUMMARY WHERE ACCOUNT_KEY = 'OMEGA';
SELECT RANK, USE_CASE, PEERS_LIVE, PEER_NAMES, EST_ANNUAL_CREDITS FROM V_USE_CASE_RECOMMENDATIONS
WHERE ACCOUNT_KEY = 'OMEGA' ORDER BY RANK;
